import os
import datetime

DEFAULT_EPLUS_VERSION = "24.2"
META_KEYS = {"__comment__"}  # optional meta key


def _as_idf_token(v):
    """None -> blank field; bool -> Yes/No; else -> str(v)."""
    if v is None:
        return ""
    if isinstance(v, bool):
        return "Yes" if v else "No"
    return str(v)


def _display_field_name(name):
    """Convert internal field key to display label for inline IDF comments."""
    return str(name).replace("_", " ").strip()


def _make_class_header(class_name):
    """Return IDFEditor-like section header block for a class."""
    cn = str(class_name).strip().upper()
    return [
        "!-   ===========  ALL OBJECTS IN CLASS: {} ===========".format(cn),
        ""
    ]


def _format_object(class_name, obj):
    """Return list of IDF lines for one object."""
    lines = []

    # Optional object comment above
    if isinstance(obj, dict) and obj.get("__comment__"):
        for c in str(obj["__comment__"]).splitlines():
            lines.append("! " + c)

    # Raw string passthrough (advanced)
    if isinstance(obj, str):
        raw = obj.strip()
        if not raw.endswith(";"):
            raw += ";"
        if not raw.lower().startswith(class_name.lower()):
            raw = class_name + ",\n    " + raw
        lines.append(raw)
        return lines

    # Dict object: use insertion order; add per-field comments
    if isinstance(obj, dict):
        items = [(k, v) for k, v in obj.items() if k not in META_KEYS]

        if len(items) == 0:
            return ["{};".format(class_name)]

        indent = "    "
        lines.append("{},".format(class_name))
        n = len(items)

        value_parts = []
        comment_labels = []
        for i, (fname, v) in enumerate(items):
            token = _as_idf_token(v)
            end = ";" if i == n - 1 else ","
            value_parts.append("{}{}".format(token, end))
            comment_labels.append("!- {}".format(_display_field_name(fname)))

        max_value_len = max(len(s) for s in value_parts) if value_parts else 0

        for value_part, comment_label in zip(value_parts, comment_labels):
            pad = " " * (max_value_len - len(value_part) + 2)
            lines.append("{}{}{}{}".format(indent, value_part, pad, comment_label))

        return lines

    # List/tuple object: order is given; no field-name comments
    if isinstance(obj, (list, tuple)):
        values = list(obj)
        if len(values) == 0:
            return ["{};".format(class_name)]

        indent = "    "
        lines.append("{},".format(class_name))
        n = len(values)

        for i, v in enumerate(values):
            token = _as_idf_token(v)
            end = ";" if i == n - 1 else ","
            lines.append("{}{}{}".format(indent, token, end))

        return lines

    raise TypeError("Object must be dict, list/tuple, or str. Got: {}".format(type(obj)))


def dict_to_idf_text(dct, default_version=DEFAULT_EPLUS_VERSION):
    if not isinstance(dct, dict):
        raise TypeError("Input d must be a dict.")

    blocks = []
    blocks.append("! Generated by GH Python dict->IDF writer (no IDD)")
    blocks.append("! Timestamp: {}".format(datetime.datetime.now().isoformat(timespec="seconds")))
    blocks.append("")

    # Optional: auto insert Version if missing
    has_version = any(str(k).strip().lower() == "version" for k in dct.keys())
    if not has_version:
        blocks.extend(_make_class_header("Version"))
        blocks.extend(_format_object("Version", [default_version]))
        blocks.append("")

    for class_name, obj_list in dct.items():
        if obj_list is None:
            continue

        # Allow single object (not list) too
        if not isinstance(obj_list, (list, tuple)):
            obj_list = [obj_list]

        cn = str(class_name).strip()

        # Class section header
        blocks.extend(_make_class_header(cn))

        for obj in obj_list:
            blocks.extend(_format_object(cn, obj))
            blocks.append("")

    return "\n".join(blocks).rstrip() + "\n"


def write_idf(dct, path):
    text = dict_to_idf_text(dct)
    folder = os.path.dirname(path)
    if folder and not os.path.isdir(folder):
        os.makedirs(folder)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
